### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mr-eshua** [mr-eshua/zowe-cli-zos-restart-jobs-plugin#2]
- [x] Initialize project using Zowe CLI sample plugin repo (#1)
- [x] Develop algorithm & add programmatic API for z/OS jobs restart (#7, #8)
- [x] Add group, command imperative API definitions (#4)
- [x] Test plugin with Zowe CLI using z/OS environment

Extra:
- [x] Update README.md
- [x] Add unit tests for plugin
- [x] Add `typedoc` comments for API calls
